#!/bin/bash

export USER="${USER:-$(whoami)}"
export VISUAL=nvim
export EDITOR=nvim
export BROWSER=microsoft-edge

# github
export GHUSER="vohaha"
export VHREPOS="$GHREPOS/$GHUSER"
alias vh="cd $VHREPOS"
alias dotf="cd $VHREPOS/dotfiles"

# HISTORY
export HISTFILE="$HOME/.histfile"
export HISTSIZE=25000
export SAVEHIST=25000
export HISTCONTROL=ignorespace

# ALIASES
_have nvim && alias vim=nvim
alias ..="cd .."
alias c="clear"
alias ls='ls --color=auto'
alias ll='ls -la'
alias chmox='chmod +x'
alias nvimrc='nvim ~/.config/nvim/'
_have bat && alias cat=bat

# enables the vi editing mode for the CLI
#set -o vi

# Enable dynamic updating of terminal window size variables $COLUMNS and $LINES.
shopt -s checkwinsize
# Allow the expansion of aliases, making them effective in scripts or interactive sessions.
shopt -s expand_aliases
# Enable recursive matching of all files and directories using the ** pattern.
#shopt -s globstar
# Include hidden files (those starting with a dot) when using * in filename expansion.
shopt -s dotglob
# Append rather than overwrite the history file, preserving command history across sessions.
shopt -s histappend
