[general]
import = ["~/.config/alacritty/local.toml"]

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 18
normal.family = "JetBrainsMono Nerd Font"

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"

[bell]
duration = 0

[keyboard]
bindings = [
    { key = "Return", mods = "Shift", chars = "\n" },
    { key = "Left",   mods = "Control", chars = "\u001b[1;5D" },
    { key = "Right",  mods = "Control", chars = "\u001b[1;5C" },
    { key = "Left",   mods = "Alt",     chars = "\u001bb" },
    { key = "Right",  mods = "Alt",     chars = "\u001bf" },
]
