import = ["~/.config/alacritty/local.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font, Bold"
italic.family = "JetBrainsMono Nerd Font, Italic"
size = 16
