#!/bin/bash

source ./configure-xdg-directories

# Install Homebrew if not already installed
if ! command -v brew &>/dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Wait for Homebrew installation to complete before proceeding
while ! command -v brew &>/dev/null; do
	sleep 1
done

brewHome=/opt/homebrew/
brewBinPath=bin/brew

# install on macOS
$brewBinPath tap homebrew/cask-fonts
$brewBinPath install jesseduffield/lazygit/lazygit
$brewBinPath install bash bash-completion@2 stow nvim alacritty tree tmux bat obsidian ripgrep fd lazygit
$brewBinPath install --cask homebrew/cask-fonts/font-jetbrains-mono-nerd-fon

# bash completion
[[ -r "$brewHome/etc/profile.d/bash_completion.sh" ]] && . "$brewHome/etc/profile.d/bash_completion.sh"

# git prompt and completion
curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh >"$XDG_CONFIG_HOME/bash/git-prompt"
curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash >"$XDG_CONFIG_HOME/bash/git-completion"

# alacritty completion
curl -L https://raw.githubusercontent.com/alacritty/alacritty/master/extra/completions/alacritty.bash >"$XDG_CONFIG_HOME/bash/alacritty-completion"

# stow files
stow -t $HOME -R */

source $HOME/.bashrc
