---
- hosts: localhost
  tasks:
    - name: Install Linux prerequisites
      ansible.builtin.apt:
        name:
          - build-essential
          - curl
          - file
          - git
          - procps
        state: present
      become: true
      when: ansible_facts["os_family"] == "Debian"

    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - htop
        - fzf
        - ripgrep
        - luarocks
        - fd
        - lazygit
        - stow

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
