#!/usr/bin/env bash
# Generates LAYERS.md from actual machine state.
# Run manually or via pre-commit hook.

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$DOTFILES_DIR/LAYERS.md"

# ── helpers ──────────────────────────────────────────────────────────────────

has() { command -v "$1" &>/dev/null; }

os() {
    case "$(uname -s)" in
        Darwin)       echo "macos" ;;
        Linux)        echo "linux" ;;
        MSYS*|MINGW*) echo "windows" ;;
        *)            echo "unknown" ;;
    esac
}
OS="$(os)"

# Returns ✓ if installed, ✗ if not
installed() { has "$1" && echo "✓" || echo "✗"; }

# Returns ✓ if file is a symlink pointing into dotfiles dir, ⚠ if exists but not stowed, ✗ if missing
stowed() {
    local file="${1/#\~/$HOME}"
    if [[ -L "$file" ]]; then
        local target
        target=$(readlink "$file")
        [[ "$target" == *"dotfiles"* ]] && echo "✓ stowed" || echo "⚠ symlink elsewhere"
    elif [[ -e "$file" ]]; then
        echo "⚠ not stowed"
    else
        echo "✗ missing"
    fi
}

# Returns ✓ if process is running, ✗ if not
running() { pgrep -x "$1" &>/dev/null && echo "✓ running" || echo "✗ not running"; }

# Check if a GUI app is installed — OS-aware
# Usage: app_installed "AppName" "macos:/Applications/App.app" "linux:flatpak:appid" "linux:which:cmd"
app_installed() {
    # name is declared for documentation; only the platform tuples are consumed.
    # shellcheck disable=SC2034
    local name="$1"; shift
    for entry in "$@"; do
        local platform="${entry%%:*}"
        local rest="${entry#*:}"
        [[ "$platform" != "$OS" ]] && continue
        local method="${rest%%:*}"
        local value="${rest#*:}"
        case "$method" in
            path)  [[ -e "$value" ]] && echo "✓" && return ;;
            which) has "$value"      && echo "✓" && return ;;
            *)     [[ -e "$value" ]] && echo "✓" && return ;;
        esac
    done
    echo "✗"
}

# ── collect state ─────────────────────────────────────────────────────────────

GENERATED_AT="$(date '+%Y-%m-%d %H:%M')"
OS_LABEL="$(case "$OS" in macos) echo "macOS" ;; linux) echo "Linux" ;; windows) echo "Windows" ;; *) echo "unknown" ;; esac)"
HOSTNAME="$(hostname -s)"

# Layer 1 — Config management
STOW_INSTALLED="$(installed stow)"
PKG_ALACRITTY="$(stowed ~/.config/alacritty/alacritty.toml)"
PKG_ALACRITTY_LOCAL="$(stowed ~/.config/alacritty/local.toml)"
PKG_SHELL="$(stowed ~/.zshrc)"
PKG_TMUX="$(stowed ~/.tmux.conf)"
PKG_ZED="$(stowed ~/.config/zed/settings.json)"
PKG_NVIM="$(stowed ~/.config/nvim/init.lua)"
PKG_GIT="$(stowed ~/.gitconfig)"

# Layer 2 — Shell
ZSH_DEFAULT="$([ "$(basename "$SHELL")" = "zsh" ] && echo "✓" || echo "✗")"
OMZ_INSTALLED="$([ -d "$HOME/.oh-my-zsh" ] && echo "✓" || echo "✗")"
SECRETS_FILE="$([ -f "$HOME/.secrets" ] && echo "✓ exists" || echo "✗ missing — API keys exposed")"

# Layer 3 — Terminal
ALACRITTY_INSTALLED="$(installed alacritty)"
TMUX_INSTALLED="$(installed tmux)"
TMUX_RUNNING="$(running tmux)"

# Layer 4 — Window & app management
case "$OS" in
    macos)
        WM_NAME="none"
        WM_INSTALLED="n/a"
        WM_RUNNING="n/a"
        ;;
    linux)
        WM_NAME="i3/sway"
        if has i3 || has sway; then
            WM_INSTALLED="✓"
        else
            WM_INSTALLED="✗"
        fi
        if pgrep -x i3 &>/dev/null || pgrep -x sway &>/dev/null; then
            WM_RUNNING="✓ running"
        else
            WM_RUNNING="✗ not running"
        fi
        ;;
    windows)
        WM_NAME="GlazeWM"
        WM_INSTALLED="$(installed glazewm)"
        WM_RUNNING="$(running glazewm)"
        ;;
    *)
        WM_NAME="unknown"
        WM_INSTALLED="✗"
        WM_RUNNING="✗ not running"
        ;;
esac

case "$OS" in
    macos)   LAUNCHER_NAME="Raycast";   LAUNCHER_INSTALLED="$(app_installed Raycast "macos:path:/Applications/Raycast.app")" ;;
    linux)   LAUNCHER_NAME="rofi";      LAUNCHER_INSTALLED="$(installed rofi)" ;;
    windows) LAUNCHER_NAME="PowerToys"; LAUNCHER_INSTALLED="$(installed powertoys)" ;;
    *)       LAUNCHER_NAME="unknown";   LAUNCHER_INSTALLED="✗" ;;
esac

# Layer 5 — Editor
ZED_INSTALLED="$(installed zed)"
NVIM_INSTALLED="$(installed nvim)"

# Layer 6 — Apps
OBSIDIAN_INSTALLED="$(app_installed Obsidian \
    "macos:path:/Applications/Obsidian.app" \
    "linux:which:obsidian" \
    "windows:path:${APPDATA:-}/Obsidian")"
BITWARDEN_INSTALLED="$(app_installed Bitwarden \
    "macos:path:/Applications/Bitwarden.app" \
    "linux:which:bw" \
    "windows:which:bw") $(has bw && echo "+ cli" || echo "")"

# ── write output ──────────────────────────────────────────────────────────────

cat > "$OUTPUT" <<EOF
# Layer Map

> Generated: $GENERATED_AT · $OS_LABEL · $HOSTNAME
>
> This file is auto-generated by \`scripts/generate-layers.sh\` on each commit.
> Do not edit manually — it will be overwritten.

---

## Layer 0 — Hardware

| Component | Details |
|---|---|
| Keyboard | Glove80 |
| Layout | TailorKey v5.2 Dual OS |
| Features | Home row mods, symbols layer, cursor layer, dual OS firmware |

Config lives in the MoErgo web editor, flashed to the keyboard.

---

## Layer 1 — Config Management

| Tool | Status |
|---|---|
| stow | $STOW_INSTALLED |

### Package Status

| Package | Config file | Status |
|---|---|---|
| shell | \`~/.zshrc\` | $PKG_SHELL |
| alacritty | \`~/.config/alacritty/alacritty.toml\` | $PKG_ALACRITTY |
| alacritty-macos | \`~/.config/alacritty/local.toml\` | $PKG_ALACRITTY_LOCAL |
| tmux | \`~/.tmux.conf\` | $PKG_TMUX |
| zed | \`~/.config/zed/settings.json\` | $PKG_ZED |
| nvim | \`~/.config/nvim/init.lua\` | $PKG_NVIM |
| git | \`~/.gitconfig\` | $PKG_GIT |

---

## Layer 2 — Shell

| Component | Status |
|---|---|
| Shell | zsh ($ZSH_DEFAULT default) |
| Framework | Oh My Zsh ($OMZ_INSTALLED installed) |
| Secrets file | $SECRETS_FILE |

---

## Layer 3 — Terminal

| Component | Status |
|---|---|
| Alacritty | $ALACRITTY_INSTALLED installed |
| tmux | $TMUX_INSTALLED installed · $TMUX_RUNNING |

---

## Layer 4 — Window & App Management

| Component | Status |
|---|---|
| $WM_NAME | $WM_INSTALLED installed · $WM_RUNNING |
| $LAUNCHER_NAME | $LAUNCHER_INSTALLED installed |

---

## Layer 5 — Editor

| Component | Status |
|---|---|
| Zed | $ZED_INSTALLED installed |
| Neovim | $NVIM_INSTALLED installed |

Zed uses vim mode + JetBrains base keymap. Neovim uses LazyVim (available, deferred).

---

## Layer 6 — Apps

| Component | Status |
|---|---|
| Obsidian | $OBSIDIAN_INSTALLED installed |
| Bitwarden | $BITWARDEN_INSTALLED installed |

These are intentionally native per OS — minimal config to capture.

---

## Cross-Platform Strategy

| Layer | macOS (personal) | Windows (work) | Linux (future) |
|---|---|---|---|
| Shell | zsh + Oh My Zsh | zsh via WSL2 | zsh |
| Terminal | Alacritty + tmux | Windows Terminal + tmux (WSL2) | Alacritty + tmux |
| Window mgmt | — (native) | GlazeWM | i3 / sway |
| App launch | Raycast | PowerToys | rofi |
| Editor | Zed + vim mode | WebStorm + IdeaVim | LazyVim |
| Keyboard | Glove80 TailorKey Dual OS | ← same firmware | ← same firmware |

The **vim keybinding layer** is the cross-platform constant — same muscle memory in Zed, WebStorm, and terminal.
EOF

echo "LAYERS.md generated → $OUTPUT"
